'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class UsuarioEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=UsuarioEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Usuario() As DbSet(Of Usuario)
    Public Overridable Property Rol() As DbSet(Of Rol)

    Public Overridable Function UsuarioAdd(nombre As String, apellidoPaterno As String, apellidoMaterno As String, idRol As Nullable(Of Integer)) As Integer
        Dim nombreParameter As ObjectParameter = If(nombre IsNot Nothing, New ObjectParameter("Nombre", nombre), New ObjectParameter("Nombre", GetType(String)))

        Dim apellidoPaternoParameter As ObjectParameter = If(apellidoPaterno IsNot Nothing, New ObjectParameter("ApellidoPaterno", apellidoPaterno), New ObjectParameter("ApellidoPaterno", GetType(String)))

        Dim apellidoMaternoParameter As ObjectParameter = If(apellidoMaterno IsNot Nothing, New ObjectParameter("ApellidoMaterno", apellidoMaterno), New ObjectParameter("ApellidoMaterno", GetType(String)))

        Dim idRolParameter As ObjectParameter = If(idRol.HasValue, New ObjectParameter("IdRol", idRol), New ObjectParameter("IdRol", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("UsuarioAdd", nombreParameter, apellidoPaternoParameter, apellidoMaternoParameter, idRolParameter)
    End Function

    Public Overridable Function UsuarioDelete(idUsuario As Nullable(Of Integer)) As Integer
        Dim idUsuarioParameter As ObjectParameter = If(idUsuario.HasValue, New ObjectParameter("IdUsuario", idUsuario), New ObjectParameter("IdUsuario", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("UsuarioDelete", idUsuarioParameter)
    End Function

    Public Overridable Function UsuarioUpdate(idUsuario As Nullable(Of Integer), nombre As String, apellidoPaterno As String, apellidoMaterno As String, idRol As Nullable(Of Integer)) As Integer
        Dim idUsuarioParameter As ObjectParameter = If(idUsuario.HasValue, New ObjectParameter("IdUsuario", idUsuario), New ObjectParameter("IdUsuario", GetType(Integer)))

        Dim nombreParameter As ObjectParameter = If(nombre IsNot Nothing, New ObjectParameter("Nombre", nombre), New ObjectParameter("Nombre", GetType(String)))

        Dim apellidoPaternoParameter As ObjectParameter = If(apellidoPaterno IsNot Nothing, New ObjectParameter("ApellidoPaterno", apellidoPaterno), New ObjectParameter("ApellidoPaterno", GetType(String)))

        Dim apellidoMaternoParameter As ObjectParameter = If(apellidoMaterno IsNot Nothing, New ObjectParameter("ApellidoMaterno", apellidoMaterno), New ObjectParameter("ApellidoMaterno", GetType(String)))

        Dim idRolParameter As ObjectParameter = If(idRol.HasValue, New ObjectParameter("IdRol", idRol), New ObjectParameter("IdRol", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("UsuarioUpdate", idUsuarioParameter, nombreParameter, apellidoPaternoParameter, apellidoMaternoParameter, idRolParameter)
    End Function

    Public Overridable Function RolGetAll() As ObjectResult(Of RolGetAll_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of RolGetAll_Result)("RolGetAll")
    End Function

    Public Overridable Function UsuarioGetAll() As ObjectResult(Of UsuarioGetAll_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of UsuarioGetAll_Result)("UsuarioGetAll")
    End Function

    Public Overridable Function UsuarioGetById(idUsuario As Nullable(Of Integer)) As ObjectResult(Of UsuarioGetById_Result)
        Dim idUsuarioParameter As ObjectParameter = If(idUsuario.HasValue, New ObjectParameter("IdUsuario", idUsuario), New ObjectParameter("IdUsuario", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of UsuarioGetById_Result)("UsuarioGetById", idUsuarioParameter)
    End Function

End Class
